-- Supabase SQL Editor에서 한 번 실행하세요.
create table if not exists public.goal_responses (
  id bigint generated by default as identity primary key,
  member_id text not null unique,
  goal text not null,
  success_metric text not null,
  current_state text not null,
  current_actions text not null default '',
  weekly_actions text not null default '',
  next_action text not null,
  obstacle text not null default '',
  support_needed text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.goal_responses enable row level security;

create or replace function public.submit_goal(
  p_member_id text, p_goal text, p_success_metric text, p_current_state text,
  p_current_actions text, p_weekly_actions text, p_next_action text,
  p_obstacle text, p_support_needed text
) returns void language plpgsql security definer set search_path = public as $$
begin
  if p_member_id !~ '^member-[0-9]{2}$' or length(trim(p_goal)) < 2 or length(trim(p_next_action)) < 2 then
    raise exception 'invalid submission';
  end if;
  insert into public.goal_responses(member_id, goal, success_metric, current_state, current_actions, weekly_actions, next_action, obstacle, support_needed)
  values (p_member_id, trim(p_goal), trim(p_success_metric), trim(p_current_state), trim(p_current_actions), trim(p_weekly_actions), trim(p_next_action), trim(p_obstacle), trim(p_support_needed))
  on conflict(member_id) do update set goal=excluded.goal, success_metric=excluded.success_metric, current_state=excluded.current_state, current_actions=excluded.current_actions, weekly_actions=excluded.weekly_actions, next_action=excluded.next_action, obstacle=excluded.obstacle, support_needed=excluded.support_needed, updated_at=now();
end; $$;

revoke all on function public.submit_goal(text,text,text,text,text,text,text,text,text) from public;
grant execute on function public.submit_goal(text,text,text,text,text,text,text,text,text) to anon, authenticated;

create or replace function public.list_submitted_member_ids()
returns table(member_id text)
language sql
security definer
set search_path = public
stable
as $$
  select goal_responses.member_id
  from public.goal_responses
  order by goal_responses.member_id;
$$;

revoke all on function public.list_submitted_member_ids() from public;
grant execute on function public.list_submitted_member_ids() to anon, authenticated;

create policy "admin can read responses" on public.goal_responses for select to authenticated using (
  (auth.jwt() ->> 'email') = 'jhmuse0829@gmail.com'
);
